name: Download

on:
  workflow_dispatch:
    inputs:
      name:
        description: Archive name (no spaces)
        required: true
        type: string
      url:
        description: MangaDex URL
        required: true
        type: string
      groupid:
        description: Group ID
        required: false
        type: string
      format:
        description: Download format
        required: true
        type: string
        default: "raw"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install
        run: python3 -m pip install mangadex-downloader

      - name: Download
        run: |
          mkdir working
          cd working
          params=()
          [[ -n "${{ inputs.groupid }}" ]] && params+=(-g "${{ inputs.groupid }}")
          python3 -m mangadex_downloader --language en -f "${{ inputs.format }}" "${{ inputs.url }}" "${params[@]}"
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Zip
        run: cd working && zip -r9 "../${{ inputs.name }}-${{ steps.date.outputs.date }}.zip" .
      
      - name: Upload
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "${{ inputs.name }}-${{ steps.date.outputs.date }}"
          prerelease: false
          files: "${{ inputs.name }}-${{ steps.date.outputs.date }}.zip"
